# Generated by Django 2.2.10 on 2020-11-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacksearch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StackSearchModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField()),
                ('pagesize', models.IntegerField()),
                ('fromdate', models.DateField()),
                ('todate', models.DateField()),
                ('min', models.DateField()),
                ('max', models.DateField()),
                ('sort', models.CharField(choices=[('1', 'activity'), ('2', 'votes'), ('3', 'creation'), ('4', 'relevance')], default='1', max_length=999)),
                ('order', models.CharField(choices=[('1', 'desc'), ('2', 'asc')], default='1', max_length=999)),
                ('q', models.CharField(max_length=999)),
                ('accepted', models.CharField(choices=[('1', 'True'), ('2', 'False')], default='1', max_length=999)),
                ('answers', models.IntegerField()),
                ('body', models.CharField(max_length=999)),
                ('closed', models.CharField(choices=[('1', 'True'), ('2', 'False')], default='2', max_length=999)),
                ('migrated', models.CharField(choices=[('1', 'True'), ('2', 'False')], default='2', max_length=999)),
                ('notice', models.CharField(choices=[('1', 'True'), ('2', 'False')], default='2', max_length=999)),
                ('nottagged', models.CharField(max_length=999)),
                ('tagged', models.CharField(max_length=999)),
                ('title', models.CharField(max_length=999)),
                ('user', models.IntegerField()),
                ('url', models.CharField(max_length=999)),
                ('views', models.IntegerField()),
                ('wiki', models.CharField(choices=[('1', 'True'), ('2', 'False')], default='1', max_length=999)),
            ],
        ),
        migrations.DeleteModel(
            name='Stackapi',
        ),
    ]
